sudo: required
language: java
env:
  - AWS_DEFAULT_REGION=us-east-1
  - IMAGE_NAME=co.jonminter/nyt-movie-picks
  - REMOTE_IMAGE_URL=265532567677.dkr.ecr.us-east-1.amazonaws.com/co.jonminter/nyt-movie-picks
  - secure: "ikI7DQlXGu1lGisS5ZCNtFQdWftE/pEMraPhzN7H0jjMvhHHERF260mPxHWDmitsgIIsOtaYz78TXlIIxXnmcWFzPm2Z1iENSLvQsUwyBz6xEA1tWQC5DRWSvJxehO9W7YPQUyD26jmDzbyQS4MJ4vbgp/pn/bHVfvNa6yVt6KJVx7/jKlfvAcoKd0ApRmlL5m7TflqewPU7RrP6yDguvkTQSprGDwKRlLxq6mNNDhsf40G86CxjyplHnL0F+9cwm2BDq8QhM/X3WLIu1De9vZQZRkyHn2KBzPSDifGyX+aqJT4yJY05kvbyTlvT8QmstpkqWnRzmsQcE0xlcQCKnboALNegt2niU+gqD8Rw5Spv+BsuUG26khAjCSRlQpcmtgX5nACFc0pXN5+0XuW5a1U+3V4OZChtMYlwUn+JDDi71XNHpfWHy6MnFbMsT/qNQgFUV1SRUX9lHpA6p+Q9fnXmXRO3yCASCC3zH17VoqLJOxEn+K3V20eOYEhIMvJwqKM8B/zRihlKxidwEZw7HFgtZNS/j7tNJId8347U2egZOqjOi2a9xItyhufQIceiNhw9IVsfVSut2Cdes38pZBp2E32V9bNO+wNcUUae540vaEx07P272xmFOa27Wc1rEkL/pdKZVBTHug3tEPgSHbZ0zTSMQfO6Uw8eYvp+56o="
  - secure: "mDsSWw4kWs5RWY6ULDWQNTJ8osuPDoljDdT6gFcIF5METuZ4IuBSngr81QAAgl0Em8QtqKCBqKpjINkWqo2sbqo/YRjI1bVHfMti6GEOvlcxaiuivKuH7W7JGwu1oo9cOBrDNCXbwYPb3NC5DQXZxrViLMXZlBfWPiA9Ye3AByuv9b4MmhiCGTqXVh1Xy2aHZnC5Nna/LvjDBQ4TJGxuxWPLZ44wJ+Iz2WEv5Y3e2ZC7ohTFwCi8rJnd2FmBUfFGYRqoO831tVntqLln/Jz7xV+EjNv6uTtG9XClAs9lMyVcbT2mpqNfDHA9nKELgtt8no5Az287O+1FiyplWa8o8izUJcIIlVZPOhWvFpl677ch0x6uGwcqSXfEG5V1d006b74NLiTbJVWmKZOuLiRAid2rjl9Zp7SSEbNoUhuG9w8qhHKiTqb33mTkECPrrowgRW8GJ8KqdAEj50uXUt+h9Z4biYjQbj1lFQqXpaNGnBvO6+RerRTZpQlqxmw1F6nxX3Tqaz4ljOoB932H89gYQm7P4o9lvA1C7lB6dleS42Gwfbh3itqrAI+yukqZUVA3HBoDeElph1rlW2m6gyTJ4DBXxO7StN5eDhlEsSromn2fAIg91NY2K4UEyDb4xOqtfTGctPabAtz6WhjVTKVpX2oRxbXVnjED8V6z5eGHnd8="
services:
  - docker
script:
  - cd api
  - ./gradlew build
after_success:
  - .travis/docker_push.sh
